/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Laboratorio-Info
 */
public class menu_GUI extends javax.swing.JFrame {

    /**
     * Creates new form menu_GUI
     */
    public menu_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        cadatrar_BTN = new javax.swing.JMenu();
        cadastrar_BTN = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        calculadora_BTN = new javax.swing.JMenuItem();
        bloco_BTN = new javax.swing.JMenuItem();
        navegador_BTN = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        encerrar_BTN = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        help_BTN = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-1, -3, 400, 280);

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 255));

        cadatrar_BTN.setText("Cliente");

        cadastrar_BTN.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        cadastrar_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/chase.png"))); // NOI18N
        cadastrar_BTN.setText("Cadastrar");
        cadastrar_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_BTNActionPerformed(evt);
            }
        });
        cadatrar_BTN.add(cadastrar_BTN);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/marshall.png"))); // NOI18N
        jMenu5.setText("Relatório");

        jMenuItem1.setText("Clientes");
        jMenu5.add(jMenuItem1);

        jMenuItem6.setText("Produto");
        jMenu5.add(jMenuItem6);

        cadatrar_BTN.add(jMenu5);

        jMenuBar1.add(cadatrar_BTN);

        jMenu2.setText("Produto");

        jMenuItem4.setText("jMenuItem4");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ferramentas");

        calculadora_BTN.setText("Calculadora");
        calculadora_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculadora_BTNActionPerformed(evt);
            }
        });
        jMenu3.add(calculadora_BTN);

        bloco_BTN.setText("Bloco de Notas");
        bloco_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloco_BTNActionPerformed(evt);
            }
        });
        jMenu3.add(bloco_BTN);

        navegador_BTN.setText("Navegador");
        navegador_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navegador_BTNActionPerformed(evt);
            }
        });
        jMenu3.add(navegador_BTN);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Sair");

        encerrar_BTN.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        encerrar_BTN.setText("Encerrar");
        encerrar_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encerrar_BTNActionPerformed(evt);
            }
        });
        jMenu4.add(encerrar_BTN);

        jMenuBar1.add(jMenu4);

        jMenu1.setText("Ajuda");

        help_BTN.setText("Help!");
        help_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                help_BTNActionPerformed(evt);
            }
        });
        jMenu1.add(help_BTN);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(400, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrar_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_BTNActionPerformed
        JOptionPane.showMessageDialog(null, " (┬┬﹏┬┬)");
    }//GEN-LAST:event_cadastrar_BTNActionPerformed

    private void encerrar_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encerrar_BTNActionPerformed
        System.exit(0);
    }//GEN-LAST:event_encerrar_BTNActionPerformed

    private void calculadora_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculadora_BTNActionPerformed
        try {
            Runtime.getRuntime().exec("cmd.exe /c start calc.exe") ;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro P001\nCalculadora não encontrada!");
        }

    }//GEN-LAST:event_calculadora_BTNActionPerformed

    private void bloco_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloco_BTNActionPerformed
        try {
            Runtime.getRuntime().exec("cmd.exe /c start notepad.exe ") ;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro P002\nBloco de Notas não encontrada!");
        }

    }//GEN-LAST:event_bloco_BTNActionPerformed

    private void help_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_help_BTNActionPerformed
        // C:\HELP.pdf
         try {
            Runtime.getRuntime().exec("cmd.exe /c start C:\\HELP.pdf ") ;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro P003\nHelp não encontrado!");
        }
    }//GEN-LAST:event_help_BTNActionPerformed

    private void navegador_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navegador_BTNActionPerformed
       try {
            Runtime.getRuntime().exec("cmd.exe /c start chrome.exe www.uol.com.br ") ;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro P004\nNavegador não encontrado!");
        }
    }//GEN-LAST:event_navegador_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem bloco_BTN;
    private javax.swing.JMenuItem cadastrar_BTN;
    private javax.swing.JMenu cadatrar_BTN;
    private javax.swing.JMenuItem calculadora_BTN;
    private javax.swing.JMenuItem encerrar_BTN;
    private javax.swing.JMenuItem help_BTN;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem navegador_BTN;
    // End of variables declaration//GEN-END:variables
}
